---
title: "Final_Project_test"
output: html_document
date: "2024-04-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#source("Final_Project.R")
library(BMI510FP)


### 1
data = c(1,0,0,0,1,1,1)
print(logLikBernoulli(data))


### 2
data_url = "https://jlucasmckay.bmi.emory.edu/global/bmi510/Labs-Materials/survival.csv"
data_file = tempfile()
download.file(data_url, data_file, method = "curl")
surv_data = read.csv(data_file)

print(surv_data)
survCurv(surv_data$status, surv_data$time)


### 3
x = c(1, 2, 3, 4, 5)
unscale(scale(x))


### 4
data = mtcars
npc = 2
approx_data = pcApprox(data, npc)
print(data)
print(approx_data)

if (!identical(dim(approx_data), dim(data))) {
  stop("Dimension test failed: The dimensions of the approximated data do not match the original data.")
}

original_means = colMeans(data)
approx_means = colMeans(approx_data)
if (any(abs(original_means - approx_means) > 1)) {
  stop("Mean test failed: The means of the approximated data significantly differ from the original data.")
}

original_sds = apply(data, 2, sd)
approx_sds = apply(approx_data, 2, sd)
if (any(abs(original_sds - approx_sds) > 1)) {
  stop("Standard deviation test failed: The standard deviations of the approximated data significantly differ from the original data.")
}

print("All tests passed successfully.")



### 5
test_data = tibble(`First name` = c("John"), `Last name` = c("Doe"))
standardized_data = standardizeNames(test_data)
print(standardized_data)


### 6
x1 <- rnorm(20, mean = 5, sd = 1)
x2 <- rnorm(20, mean = 6, sd = 1)

minimumN(x1)
minimumN(x1, x2)


### 7
url = "https://redcap.emory.edu/api/"
Sys.setenv("REDCAP_API_TOKEN" = "6189879441F5C29A25245880677488BF")
print(downloadRedcapReport("REDCAP_API_TOKEN", url, '46524'))

```
